per_listener_settings true
persistence false
log_dest stdout
log_type error
log_type warning
log_type notice

listener 1883
allow_anonymous true

listener 1884
allow_anonymous false
password_file /mosquitto/generated/passwords

listener 8883
allow_anonymous true
cafile /mosquitto/generated/ca.crt
certfile /mosquitto/generated/server.crt
keyfile /mosquitto/generated/server.key

listener 9001
protocol websockets
allow_anonymous true

